name: nautilus # you probably want to 'snapcraft register <name>'
version: '43.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: The default file manager of the GNOME desktop # 79 char long summary
description: |
  Files, also known as Nautilus, is the default file manager of the GNOME desktop. 
  It provides a simple and integrated way of managing your files and browsing your file system.

confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  nautilus:
    plugin: dump
    source: https://download.gnome.org/sources/nautilus/43/nautilus-43.1.tar.xz

apps:
  nautilus:
    command: nautilus
